spring:
  datasource:
    url: jdbc:h2:file:./target/mdg-local-demo;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

logging:
  level:
    com.datagenerator: info
